package com.chakmidlot.usefulface.english


val vocabulary = listOf(
    Pair("abide", "by"),
    Pair("abstain", "from"),
    Pair("accuse", "smb of"),
    Pair("add", "to"),
    Pair("adhere", "to"),
    Pair("agree", "with"),
    Pair("aim", "at/for"),
    Pair("allow", "for"),
    Pair("apologise", "to someone for smt"),
    Pair("apply", "for"),
    Pair("approve", "of"),
    Pair("argue", "with/about"),
    Pair("arrest", "smb for"),
    Pair("ask", "for"),
    Pair("attend", "to"),
    Pair("believe", "in"),
    Pair("belong", "to"),
    Pair("blame", "smb for"),
    Pair("boast", "about"),
    Pair("borrow", "smb from smb"),
    Pair("call", "for"),
    Pair("care", "for"),
    Pair("choose", "between"),
    Pair("comment", "on"),
    Pair("compare", "with"),
    Pair("complain", "about"),
    Pair("according", "to"),
    Pair("accustomed", "to"),
    Pair("afraid", "of"),
    Pair("annoyed", "with/about/at"),
    Pair("anxious", "about"),
    Pair("ashamed", "of"),
    Pair("astonished", "at"),
    Pair("attached", "to"),
    Pair("aware", "of"),
    Pair("delighted", "at/about"),
    Pair("different", "from"),
    Pair("dissatisfied", "with"),
    Pair("doubtful", "about"),
    Pair("enthusiastic", "about"),
    Pair("envious", "of"),
    Pair("excited", "about"),
    Pair("famous", "for"),
    Pair("fed", "up with"),
    Pair("fond", "of"),
    Pair("frightened", "of"),
    Pair("friendly", "with"),
    Pair("good", "at"),
    Pair("guilty", "of"),
    Pair("incapable", "of"),
    Pair("interested", "in"),
    Pair("jealous", "of"),
    Pair("_ agreement", "in"),
    Pair("attack", "on"),
    Pair("attitude", "towards"),
    Pair("_ behalf of", "on"),
    Pair("comparison", "between"),
    Pair("_ condition (that)", "on"),
    Pair("connection", "between"),
    Pair("cruelty", "towards"),
    Pair("decrease", "in"),
    Pair("delay", "in"),
    Pair("difference", "between/of"),
    Pair("difficulty", "in/with"),
    Pair("disadvantage", "of"),
    Pair("_ doubt", "in"),
    Pair("_ guarantee", "under"),
    Pair("increase", "in"),
    Pair("information", "about"),
    Pair("intention", "of"),
    Pair("knowledge", "of"),
    Pair("need", "for"),
    Pair("notice", "of"),
    Pair("_ order", "in"),
    Pair("pleasure", "in"),
    Pair("_ power", "in"),
    Pair("_ practice", "in"),
    Pair("preference", "for"),
    Pair("concentrate", "on"),
    Pair("conform", "to"),
    Pair("congratulate", "on"),
    Pair("consent", "to"),
    Pair("consist", "of"),
    Pair("deal", "with"),
    Pair("decide", "on"),
    Pair("excel", "at/in"),
    Pair("excuse", "smb for"),
    Pair("face", "up to"),
    Pair("forgive", "smb for"),
    Pair("hear", "of/about"),
    Pair("hope", "for"),
    Pair("insist", "on"),
    Pair("interfere", "with/in"),
    Pair("joke", "about"),
    Pair("laugh", "at"),
    Pair("lend", "smb to smb"),
    Pair("listen", "to"),
    Pair("long", "for"),
    Pair("mistake", "smb for"),
    Pair("object", "to"),
    Pair("pay", "for"),
    Pair("praise", "smb for"),
    Pair("prepare", "for"),
    Pair("present", "smb with"),
    Pair("prevent", "smb from"),
    Pair("protest", "about"),
    Pair("keen", "on"),
    Pair("kind", "to"),
    Pair("mad", "at/about"),
    Pair("opposed", "to"),
    Pair("pleased", "with"),
    Pair("popular", "with"),
    Pair("proud", "of"),
    Pair("puzzled", "by/about"),
    Pair("safe", "from"),
    Pair("satisfied", "with"),
    Pair("sensitive", "to(wards)"),
    Pair("serious", "about"),
    Pair("sick", "of"),
    Pair("similar", "to"),
    Pair("sorry", "for/about"),
    Pair("suspicious", "of"),
    Pair("sympathetic", "to(wards)"),
    Pair("tired", "of"),
    Pair("typical", "of"),
    Pair("unaware", "of"),
    Pair("used", "to"),
    Pair("protection", "from"),
    Pair("reaction", "to"),
    Pair("reason", "for"),
    Pair("reduction", "in"),
    Pair("report", "on"),
    Pair("result", "of"),
    Pair("rise", "in"),
    Pair("_ risk", "at"),
    Pair("room", "for"),
    Pair("solution", "to"),
    Pair("_ strike", "on"),
    Pair("_ suspicion of", "on"),
    Pair("_ suspicion", "under"),
    Pair("_ theory", "in"),
    Pair("_ trouble", "in"),
    Pair("trouble", "with"),
    Pair("provide", "smb with"),
    Pair("punish", "smb for"),
    Pair("refer", "to"),
    Pair("rely", "on"),
    Pair("run", "for"),
    Pair("save", "smb from"),
    Pair("sentence", "smb to"),
    Pair("smile", "at"),
    Pair("succeed", "in"),
    Pair("suffer", "from"),
    Pair("stand", "for"),
    Pair("talk", "to smb about smb"),
    Pair("thank", "smb for"),
    Pair("think", "of/about"),
    Pair("volunteer", "to"),
    Pair("wait", "for"),
    Pair("warn", "smb about"),
    Pair("worry", "about")
)
